### ISSUE TITLE
Template repo?

### ISSUE THREAD

**Issue by ferdnyc** [jonaths/minimum-python#2]
Given its [stated purpose](https://medium.com/@jonathanserrano/use-this-flexible-python-file-structure-to-keep-your-code-tidy-b14f58785a62), why not make this (formally) a [GitHub template repo](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository)?

**Comment by jonaths** [comment]
Just did as you suggested! I was not aware it was possible.
